[package]
name = "example-rivet-barebones-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dotenv = "0.15.0"
rivet-matchmaker = "0.0.5"
tokio = { version = "1", features = ["full"] }
tower = "0.4"

